apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: test-rhoai-demo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-rhoai-demo 
  name: test-rhoai-demo
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: test-rhoai-demo 
